name: GitHub & Docker Artifacts

on:
  push:
    branches: ["main"]

jobs:
  deploy_github_artifact:
    name: Deploy GitHub Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "19"
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Mark compile.sh as executable
        run: chmod +x compile.sh
      - name: Run compile.sh
        run: ./compile.sh
      - name: Create zip of build
        run: zip -r portal.zip build/*
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA") && gh release create "$COMMIT_HASH" --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${COMMIT_HASH}" \./portal.zip --generate-notes --latest
  deploy_dockerhub_artifact:
    name: Deploy DockerHub Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal:latest,${{ secrets.DOCKERHUB_USERNAME }}/portal:${{ github.sha }}
